config/routes.rb
Rails.application.routes.draw do

  root to:'pages#index'

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :series, :path => '/admin/series'
  resources :editors, :path => '/admin/editors'
  resources :slides, :path => '/admin/slides'
  devise_for :users, :skip => [:registrations, :sessions]                                          
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get 'admin/change_password' => 'devise/registrations#edit', :as => 'edit_user_registration'    
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  get '/admin' => 'admin#index', as: :admin
  get "/admin/enqueue_elibri" => "admin#enqueue_elibri", as: :enqueue_elibri
  get '/zapowiedzi' => 'pages#preorders', as: 'preorders'
  get '/lista-produktow' => 'pages#products_list', as: 'products_list'
  get '/foreign-rights' => 'pages#foreign_rights', as: 'foreign_rights'
  get '/kontakt' => 'pages#contact', as: 'contact'
  get '/seria/:id' => 'pages#by_series', as: 'by_series'
  get '/autor/:id' => 'pages#author', as: 'autor'
  get '/book/:id' => 'book#show'
  get '/preview/:id' => "book#preview", as: :preview
  get 'admin/slide/:id' => 'slides#edit', as: 'slide_show'

  get ':id' => "book#show", as: :book

end

app/models/slide.rb
class Slide < ApplicationRecord
  mount_uploader :image, ImageUploader
  scope :active, lambda { where("start_at is null or start_at <= ?", Date.today).where("end_at is null or end_at > ?", Date.today) }
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  before_action :set_slide, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /slides
  # GET /slides.json
  def index
    @slides = Slide.all
    @slide = Slide.new
  end

  # GET /slides/1
  # GET /slides/1.json
  def show
  end

  # GET /slides/new
  def new
    @slide = Slide.new
  end

  # GET /slides/1/edit
  def edit
  end

  # POST /slides
  # POST /slides.json
  def create
    @slide = Slide.new(slide_params)

    respond_to do |format|
      if @slide.save
        format.html { redirect_to slides_path, notice: 'Slide was successfully created.' }
        format.json { render :show, status: :created, location: @slide }
      else
        format.html { render :new }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slides/1
  # PATCH/PUT /slides/1.json
  def update
    respond_to do |format|
      if @slide.update(slide_params)
        format.html { redirect_to slides_path, notice: 'Slide was successfully updated.' }
        format.json { render :show, status: :ok, location: @slide }
      else
        format.html { render :edit }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    @slide.destroy
    respond_to do |format|
      format.html { redirect_to slides_path, notice: 'Slide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slide
      @slide = Slide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slide_params
      params.require(:slide).permit(:image, :link, :start_at, :end_at)
    end
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/slides/_form.html.erb
<%= form_for @slide do |f| %>
    <% if @slide.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@slide.errors.count, "error") %> prohibited this slide from being saved:</h2>
        <ul>
        <% @slide.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class='single-slide'>
      <div><%= image_tag(slide.image) %></div>
    </div>
    <h3><%= f.label 'image', 'Zmień obrazek' %></h3>
    <%= f.file_field :image %>
    <h4>Podlinkuj obrazek:</h4>
    <%= f.text_field :link, placeholder:"#{slide.link}" %>
    <p>od: </p><%= f.date_select :start_at %>
    <p>do: </p><%= f.date_select :end_at %>

    <%= f.submit('Zapisz', class: 'btn btn-success') %>
  <% end %>

app/views/slides/edit.html.erb
<h1>Edytuj Slide</h1>

<%= render 'form', slide: @slide %>

app/views/slides/index.html.erb
<div class='row'>
  <% @slides.each do |slide| %>
    <div class='col-sm-12 single-slide'>
      <div><%= image_tag(slide.image) %></div>
      <span><u><%= slide.link %></u></span>
      <span>od: <%= slide.start_at %></span>
      <span>do: <%= slide.end_at %></span>
      <%= link_to 'Edit', slide_show_url(slide), class: 'btn btn-primary' %>
      <%= link_to 'Destroy', slide, method: :delete, data: { confirm: 'Czy na pewno chcesz usunąć obrazek?' }, class: 'btn btn-danger' %>
    </div>
  <% end %>
</div>

<div class='row'>
  <div class='col-sm-12'>
    <%= form_for @slide do |f| %>
      <% if @slide.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@slide.errors.count, "error") %> prohibited this slide from being saved:</h2>
          <ul>
          <% @slide.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <h3><%= f.label 'image', 'Wybierz obrazek' %></h3>
      <p>Wymiary 820x300</p>
      <%= f.file_field :image %>
      <h4>Podlinkuj obrazek:</h4>
      <p>Wpisz pełny adres strony np <mark>https://www.example.pl/</mark></p>
      <%= f.text_field :link %>
      <h4>Wybierz kiedy ma być widoczny obrazek:</h4>
      <p>od: </p><%= f.date_select :start_at %>
      <p>do: </p><%= f.date_select :end_at, {:include_blank => true, :default => nil} %>

      <%= f.submit('Dodaj obrazek', class: 'btn btn-success') %>
    <% end %>
  </div>
</div>

app/views/slides/new.html.erb
<h1>New Slide</h1>

<%= render 'form', slide: @slide %>

<%= link_to 'Back', slides_path %>

app/views/slides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@slide.image) %>
</p>

<%= link_to 'Edit', edit_slide_path(@slide) %> |
<%= link_to 'Back', slides_path %>