config/routes.rb
Rails.application.routes.draw do

  root to:'pages#index'

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :series, :path => '/admin/series'
  resources :editors, :path => '/admin/editors'
  resources :slides, :path => '/admin/slides'
  devise_for :users, :skip => [:registrations, :sessions]                                          
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get 'admin/change_password' => 'devise/registrations#edit', :as => 'edit_user_registration'    
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  get '/admin' => 'admin#index', as: :admin
  get "/admin/enqueue_elibri" => "admin#enqueue_elibri", as: :enqueue_elibri
  get '/zapowiedzi' => 'pages#preorders', as: 'preorders'
  get '/lista-produktow' => 'pages#products_list', as: 'products_list'
  get '/foreign-rights' => 'pages#foreign_rights', as: 'foreign_rights'
  get '/kontakt' => 'pages#contact', as: 'contact'
  get '/seria/:id' => 'pages#by_series', as: 'by_series'
  get '/autor/:id' => 'pages#author', as: 'autor'
  get '/book/:id' => 'book#show'
  get '/preview/:id' => "book#preview", as: :preview
  get 'admin/slide/:id' => 'slides#edit', as: 'slide_show'

  get ':id' => "book#show", as: :book

end

app/views/pages/_header.html.erb
<% if user_signed_in? %>
  <div class='admin-options'>
    <% if !current_page?(edit_user_registration_path) %>
      <%= link_to "Zmień hasło", edit_user_registration_path %>
    <% end %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
    <%= link_to "Panel administratora", admin_path %>
  </div>
<% end %>

<div class='row'>
  <div class='col-sm-12'>
  <%= link_to image_tag('logo.png'), root_path, class: 'logo' %>
  </div>
</div>
<div class='row'>
  <div class='col-sm-12'>
    <div class='nav main-navigation'>
      <li role='presentation'>
        <%= link_to 'Zapowiedzi', preorders_path %>
      </li>
      <li role='presentation'>
        <%= link_to 'Nasze książki', products_list_path %>
      </li>
      <li role='presentation'>
        <%= link_to 'Foreign rights', foreign_rights_path %>
      </li>
      <li role='presentation'>
        <%= link_to 'Kontakt', contact_path %>
      </li>
    </div>
  </div>
</div>

app/views/pages/author.html.erb
<% @authors_books.each do |book| %>
  <div class='col-sm-4 col-xs-6 book-container'>
    <div class='cover'>
      <%=link_to book, class: 'cover' do %>
        <%= image_tag book.cover.url(:thumb) %>
      <% end %>
    </div>
    <div class='book-info'>
      <p class='book-title'>
        <%= link_to book.title, book %>
      </p>
      <p class='release-date'>Data premiery <%= book.premiere_as_date %></p>
    </div>
  </div>
<% end %>

app/views/pages/contact.html.erb
<div class='row editor-content'>
  <div class="col-sm-12">
    <% unless @editors.nil? %> 
      <p><%= raw(@editors.content) %></p>
    <% end %>
  </div>
</div>

app/views/pages/foreign_rights.html.erb
<div class='row editor-content'>
  <div class="col-sm-12">
    <% unless @editors.nil? %> 
        <p><%= raw(@editors.content) %></p>
    <% end %>
  </div>
</div>

app/views/pages/index.html.erb
<div class='row'>
  <% if Slide.count > 0 %>
    <div class='col-sm-12'>
      <div id='carousel' class='carousel slide' data-ride='carousel' data-interval='5000'>
        <ol class='carousel-indicators'>
          <% @slides.each_with_index do |slide, index| %>
            <li data-target="#carousel" data-slide-to="<%= index %>" class="<% if index == 0 %> active <% end %>"></li>
          <% end %>
        </ol>
        <div class='carousel-inner' role='listbox'>
          <% @slides.each_with_index do |slide, index| %>
            <div class="item <% if index == 0 %> active <% end %> ">
              <% if slide.link.blank? %>
                <%= image_tag(slide.image) %>
              <% else %>
                <%= link_to "#{slide.link}" do %>
                  <%= image_tag(slide.image) %>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% elsif Slide.count == 0 %>
    <div class='row slider-row'>
    </div>
  <% end %>
</div>
<div class='row'>
  <div class='col-xs-6 two-in-row-book-container'>
    <p class='section-title'>Zapowiedzi</p>
    <% for book in @announcement_books %>
      <div class='col-sm-6'>
        <%=link_to book, class: 'cover' do %>
          <%= image_tag book.cover.url(:thumb) %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class='col-xs-6'>
    <p class='section-title'>Nowości</p>
    <% @new_books.each do |book| %>
      <div class='col-sm-4 col-xs-12 small-book-container'>
        <%=link_to book, class: 'cover' do %> 
          <%= image_tag book.cover.url(:thumb) %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<div class='row series'>
  <div class='col-sm-12'>
    <p class='section-title'>Serie</p>
    <% @displayed_series.each do |series| %>
      <ul class='series-list'>
        <li>
          <%= link_to by_series_path(id: series.name.parameterize), class: 'series-title' do %>
            <%= series.name %>
            <% unless series.icon.blank? %>
              <%= image_tag(series.icon, class: 'series-icon pull-left') %>
            <% end %>
          <% end %>
          <p><%= series.description %></p>
          <% series.books.each do |book| %>
            <%=link_to book, class: 'cover' do %>
              <%= image_tag book.cover.url(:thumb) %>
            <% end %>
          <% end %>
        </li>
      </ul>
    <% end %>
  </div>
</div>

app/views/pages/preorders.html.erb
<div class='row'>
  <% @announcement_books.each do | book | %>
    <div class='col-sm-4 col-xs-6 book-container'>
      <div class='cover'>
        <%=link_to (image_tag (book.cover.url(:thumb))), book, class: 'cover' %>
      </div>
      <div class='book-info'>
        <p class='book-title'><%= link_to book.title, book %></p>
        <p class='book-author'><%= book.authors.join(', ') %></p>
        <p class='release-date'>Data premiery <%= book.premiere_as_date %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/products_list.html.erb
<% if @results %>
  <div class='row'>
    <div class='col-sm-12'>
      <%= paginate @results %>
    </div>
  </div>
<% end %>
<div class='row'>
  <% (@results || @books).each do |book| %>
    <div class='col-sm-4 col-xs-6 book-container'>
      <div class='cover'>
        <%=link_to book, class: 'cover' do %>
          <%= image_tag book.cover.url(:thumb) %>
        <% end %>
      </div>
      <div class='book-info'>
        <p class='book-title'>
          <%= link_to book.title, book %>
        </p>
        <% book.authors.each do |author| %>
          <%= link_to autor_path(id: author.parameterize), class: 'author-link' do %>
            <%= author %>
          <% end %>
        <% end %>
        <p class='release-date'>Data premiery <%= book.premiere_as_date %></p>
      </div>
    </div>
  <% end %>
</div>

<% if @results %>
  <div class='row'>
    <div class='col-sm-12'>
      <%= paginate @results %>
    </div>
  </div>
<% end %>