config/routes.rb
Rails.application.routes.draw do

  root to:'pages#index'

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :series, :path => '/admin/series'
  resources :editors, :path => '/admin/editors'
  resources :slides, :path => '/admin/slides'
  devise_for :users, :skip => [:registrations, :sessions]                                          
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get 'admin/change_password' => 'devise/registrations#edit', :as => 'edit_user_registration'    
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  get '/admin' => 'admin#index', as: :admin
  get "/admin/enqueue_elibri" => "admin#enqueue_elibri", as: :enqueue_elibri
  get '/zapowiedzi' => 'pages#preorders', as: 'preorders'
  get '/lista-produktow' => 'pages#products_list', as: 'products_list'
  get '/foreign-rights' => 'pages#foreign_rights', as: 'foreign_rights'
  get '/kontakt' => 'pages#contact', as: 'contact'
  get '/seria/:id' => 'pages#by_series', as: 'by_series'
  get '/autor/:id' => 'pages#author', as: 'autor'
  get '/book/:id' => 'book#show'
  get '/preview/:id' => "book#preview", as: :preview
  get 'admin/slide/:id' => 'slides#edit', as: 'slide_show'

  get ':id' => "book#show", as: :book

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_series, only: [:show, :edit, :update, :destroy]

  # GET /series
  # GET /series.json
  def index
    @series = Series.new
    @displayed_series = Series.order(:position)
    @series_list = Book.all.map { |b| [b.collection_name] + b.series.map(&:name) }.flatten.compact.uniq.sort
  end

  # GET /series/1
  # GET /series/1.json
  def show
    redirect_to '/admin/series'
  end

  # GET /series/new
  def new
    @series = Series.new
  end

  # GET /series/1/edit
  def edit
    @series_list = Book.all.map { |b| [b.collection_name] + b.series.map(&:name) }.flatten.compact.uniq.sort
  end

  # POST /series
  # POST /series.json
  def create
    @series = Series.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to '/admin/series', notice: 'Series was successfully created.' }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1
  # PATCH/PUT /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to '/admin/series', notice: 'Series was successfully updated.' }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to '/admin/series', notice: 'Series was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.require(:series).permit(:name, :description, :position, :icon)
    end
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_form.html.erb
<%= form_for(series) do |f| %>
  <% if series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% series.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= image_tag(series.icon, class: 'series-icon') %>
    <h4><%= series.name %></h4>
    <p>Dodaj logo serii</p>
    <%= f.file_field :icon %>
    <p>Pozycja na liście:</p>
    <%= f.number_field :position %>
    <p>Zmień opis serii:</p>
    <%= f.text_area :description %>
    <%= f.submit('Zapisz serię', class: 'btn btn-success') %>
<% end %>

app/views/series/edit.html.erb
<h1>Edytuj Serię</h1>

<%= render 'form', series: @series %>

app/views/series/index.html.erb
<h3>Dodane serie</h3>
<ul class='displayed-series-list'>
  <% @displayed_series.each do |series| %>
    <li>
      <% unless series.icon.blank? %>
        <%= image_tag(series.icon, class: 'series-icon') %>
      <% end %>
      <h4><u><%= series.name %></u></h4>
      <p><span>pozycja na liście <b><%= series.position %></b></p>
      <p><%= series.description %></p>
      <%= link_to 'Edit', edit_series_path(series), class: 'btn btn-primary' %>
      <%= link_to 'Destroy', series, method: :delete, data: { confirm: 'Czy na pewno chcesz usunąć serię?'}, class: 'btn btn-danger' %>
    </li>
  <% end %>
</ul>

<div class='row'>
  <div class='col-sm-12 series-form'>
    <%= form_for(@series) do |f| %>
      <p>Wybierz serię:</p>
      <%= f.select :name, options_for_select(@series_list) %>
      <p>Dodaj logo serii</p>
      <%= f.file_field :icon %>
      <p>Pozycja na liście:</p>
      <%= f.number_field :position %>
      <p>Dodaj opis serii:</p>
      <%= f.text_area :description %>
      <%= f.submit('Dodaj serię', class: 'btn btn-success') %>
    <% end %>
</div>

app/views/series/new.html.erb
<h1>New Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Back', series_index_path %>

app/views/series/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @series.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @series.description %>
</p>

<%= link_to 'Edit', edit_series_path(@series) %> |
<%= link_to 'Back', series_index_path %>